# Generated by Django 5.0.6 on 2024-06-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_is_staff_customuser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
